import { jsPDF } from 'jspdf';
import type { Estimate, EstimateLineItem } from '../shared/types';

export function generateProposal(estimate: Estimate): Blob {
  const doc = new jsPDF();
  
  // Cover Page
  doc.setFontSize(24);
  doc.text('Project Estimate', 20, 30);
  doc.setFontSize(12);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 50);
  doc.text(`Project: ${estimate.projectName}`, 20, 60);
  doc.text(`Client: ${estimate.client}`, 20, 70);
  doc.text(`Status: ${estimate.status.toUpperCase()}`, 20, 80);
  
  // Line Items Table
  doc.setFontSize(14);
  doc.text('Line Items', 20, 100);
  
  // Table header
  doc.setFontSize(10);
  doc.setFillColor(240, 240, 240);
  doc.rect(20, 105, 170, 8, 'F');
  doc.text('Description', 22, 110);
  doc.text('Qty', 100, 110);
  doc.text('Unit Price', 120, 110);
  doc.text('Total', 160, 110);
  
  let y = 120;
  
  // Group line items by category
  const categories = [...new Set(estimate.lineItems.map(item => item.category))];
  
  for (const category of categories) {
    // Category header
    doc.setFontSize(11);
    doc.setTextColor(0, 51, 102);
    doc.text(category, 20, y);
    y += 8;
    
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(9);
    
    const categoryItems = estimate.lineItems.filter(item => item.category === category);
    for (const item of categoryItems) {
      // Check if we need a new page
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      
      doc.text(item.description.substring(0, 60), 22, y);
      doc.text(item.quantity.toString(), 100, y);
      doc.text(`$${item.unitPrice.toFixed(2)}`, 120, y);
      doc.text(`$${item.total.toFixed(2)}`, 160, y);
      y += 7;
    }
    
    y += 5;
  }
  
  // Summary section
  y += 10;
  if (y > 250) {
    doc.addPage();
    y = 20;
  }
  
  doc.setDrawColor(200, 200, 200);
  doc.line(20, y, 190, y);
  y += 10;
  
  doc.setFontSize(16);
  doc.setTextColor(0, 51, 102);
  doc.text('Total:', 120, y);
  doc.text(`$${estimate.total.toFixed(2)}`, 160, y);
  
  // Footer
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by VoltEstimate Pro', 20, 290);
  doc.text(`Estimate ID: ${estimate.id}`, 160, 290);
  
  return doc.output('blob');
}

export function downloadProposal(estimate: Estimate): void {
  const blob = generateProposal(estimate);
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `estimate-${estimate.id}.pdf`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
